name: Terraform Infra Workflow Pipeline

on:
  workflow_dispatch:

jobs:
  Terraform_Runner:
    name: Runner
    runs-on: ubuntu-latest
    steps:
      - name: $name Setup
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: "1.14.6"

      - name: Checkout Action
        uses: actions/checkout@v6.0.2

  # Azure_Login:
  #   name: Az Login
  #   steps:
  #     - name: Azure Login Command
        
  

        
