name: Terraform Infra Workflow Pipeline

on:
  workflow_dispatch:

jobs:
  Terraform_Runner:
    name: Runner
    runs-on: ubuntu-latest
    steps:
      - name: ${{ vars.name }} Setup
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: "1.14.6"

      - name: Checkout Action
        uses: actions/checkout@v6.0.2
    
      - name: Az Login
        uses: Azure/login@v3
        with:
          creds: ${{ secrets.AZURE_LOGIN }}
          

  

        
