name: Terraform Init

on:
  workflow_dispatch:
    pull:
      branches:
        - main
        - dev
        - feature

    push:
      branches:
        - main
        - dev
        - feature

jobs:
  terraform_init:
    name: Terrafom Init
    runs-on: ubuntu-slim
    steps:
      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v2.0.3

      - name: Checkout
        uses: actions/checkout@v6

      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
    # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Terraform Init
        run: terraform init
